pub mod cli;
pub mod client;
pub mod config;
pub mod detect;
pub mod logging;
mod metadata_tokens;
pub mod model;
pub mod pane;
pub mod persist;
mod platform;
mod plugin;
mod plugin_command;
pub mod protocol;
pub mod pty;
pub mod server;
pub mod terminal;
mod terminal_notify;
